<?php
$Customers  = "CREATE TABLE Customers 
(id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
second_name VARCHAR(30) NOT NULL,
phone_no VARCHAR(30) NOT NULL,
password VARCHAR(50) NOT NULL,
email VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)";

$admin = "CREATE TABLE Adminuser
(id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
second_name VARCHAR(30) NOT NULL,
phone_no VARCHAR(30) NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(50)
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)";);

$books = "CREATE TABLE Books 
(id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(20) NOT NULL,
author_id INT(6) NOT NULL,
publish_year YEAR,
price FLOAT(10) NOT NULL,
stock INT(100) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)";

$authors = "CREATE TABLE Authors(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
secondname VARCHAR(30) NOT NULL,
bio VARCHAR(255))";

$Orders = "CREATE TABLE Orders (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
customer_id INT(6) NOT NULL,
order_items_id INT(6),
status VARCHAR(20) NOT NULL,
totalamount FLOAT(100) NOT NULL,
order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)";

$Order_items = "CREATE TABLE Order_items(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
book_id INT(6),
price FLOAT(100),
quantity INT(100))";

C:\Projects\bookstore\schema